version: "3.9"

services:

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: payout
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  api:
    build: ./api
    ports:
      - "8080:8080"
    environment:
      APP_ORIGIN: ${APP_ORIGIN}
      API_BASE_URL: ${API_BASE_URL}
    depends_on:
      - db

  web:
    build: ./app
    ports:
      - "5173:5173"
    environment:
      VITE_API_BASE_URL: ${API_BASE_URL}
    volumes:
      - ./app:/app
      - /app/node_modules